server {
    listen 443 ssl default_server;
	listen [::]:443 ssl default_server;

	ssl_protocols TLSv1.2 TLSv1.3;
	ssl_certificate ${CRED_PATH}/${CRED_CERT}; #/etc/nginx/certs/nginx-selfsigned.crt;
    ssl_certificate_key ${CRED_PATH}/${CRED_KEY}; #/etc/nginx/certs/nginx-selfsigned.key;

    root /var/www/html;
    index index.php index.html index.htm index.nginx-debian.html;

	server_name ${DOMAIN_NAME}; #dsewlia.42.fr;

    # location / {
    #     try_files $uri $uri/ =404;
    # }

	location / {
    	try_files $uri $uri/ /index.php?$args;
	}

    location ~ \.php$ {
		include snippets/fastcgi-php.conf;

		fastcgi_pass wordpress:9000;
    }
}

# server {
#     listen 443 ssl;
#     server_name dsewlia.42.fr;

#     ssl_certificate /etc/nginx/ssl/dsewlia.crt;
#     ssl_certificate_key /etc/nginx/ssl/dsewlia.key;

#     ssl_protocols TLSv1.2 TLSv1.3;
	
# 	root /var/www/html;
# 	index index.php index.nginx-debian.html index.html;
	
# 	location / {
# 		try_files $uri $uri/ /index.php$is_args$args;
# 	}
	
# 	location ~ \.php$ {
# 		include snippets/fastcgi-php.conf;
# 		fastcgi_pass wordpress:9000;
# 		fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
# 		include fastcgi_params;
# 	}
# }